stages:
  - build
  - test
  - deploy

build-develop:
  except:
#      - master
      - tags
  stage: build
  tags:
      - BaseX-9.2
  variables:
     GIT_STRATEGY: clone
     GIT_CLONE_PATH: $CI_BUILDS_DIR/vicav-app
     HOME: /home/gitlab-runner
  script:
    - pwd
    - cd $GIT_CLONE_PATH

installation:
  except:
#      - master
      - tags
  stage: test
  tags:
      - BaseX-9.2
  variables:
     GIT_CLONE_PATH: $CI_BUILDS_DIR/vicav-app
     HOME: /home/gitlab-runner
  script:
    - cd $CI_BUILDS_DIR
    - git clone https://$OPENAPI_USER:$OPENAPI_PW@github.com/acdh-oeaw/vicav-content.git --branch master
    - cd vicav-content
    - for d in $(ls | grep vicav_); do cp -r ${d} $GIT_CLONE_PATH/$d; done;
    # - npm install
    # - node_modules/.bin/mocha test.js
    # - cd $CI_BUILDS_DIR
    # - rm -rf openapi4restxq
    # - git clone https://$OPENAPI_USER:$OPENAPI_PW@gitlab.com/acdh-oeaw/openapi4restxq.git --branch master_basex
    # - cd openapi4restxq
    - cd $GIT_CLONE_PATH
    # - mkdir screenshots-actual
    # - mkdir screenshots-diff
    # - cd screenshots-actual
    # - '# wait a little for BaseX to pick up the changes'
    # - sleep 1.5 
    - chromium-browser --headless --disable-gpu --no-sandbox --screenshot --window-size=1280,1696 --virtual-time-budget=10000 http://localhost:8984/vicav
    #- mv screenshot.png
    # - diffpng --output ../screenshots-diff/vleserver_basex vleserver_basex.png ../screenshots/vleserver_basex.png
  after_script:
    - rm -rf $GIT_CLONE_PATH*

  artifacts:
    when: on_failure
    expire_in: 1 day
    paths:
      - $GIT_CLONE_PATH/screenshot.png

clean-testbench:
  stage: deploy
  tags:
      - BaseX-9.2
  variables:
     GIT_CLONE_PATH: $CI_BUILDS_DIR/vicav-app
  script:
      - rm -rf $GIT_CLONE_PATH*
      - rm -rf $CI_BUILDS_DIR/openapi4restxq
      - mkdir -p $GIT_CLONE_PATH
