stages:
  - build
  - test
  - cleanup

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_BUILDS_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

build-develop:
  except:
      - tags
  stage: build
  tags:
      - BaseX-9.2
  variables:
     GIT_STRATEGY: clone
     GIT_CLONE_PATH: $CI_BUILDS_DIR/vicav_webapp
     VICAV_CONTENT_REPO: https://github.com/acdh-oeaw/vicav-content.git
     HOME: /home/gitlab-runner
  script:
    - pwd
    - cd $GIT_CLONE_PATH
    - npm ci
    # check Cypress binary path and cached versions
    # useful to make sure we are not carrying around old versions
    - npx cypress cache path
    - npx cypress cache list
    - $(npm bin)/cypress verify
    - cd $CI_BUILDS_DIR
    - ./vicav_webapp/scripts/gitlab-runner-setup.sh
    - mkdir -p $CI_BUILDS_DIR/vicav_webapp/artifacts
    - rm -rf $CI_BUILDS_DIR/vicav_webapp/artifacts/*  2>/dev/null
    
run_tests:
  except:
      - tags
  stage: test
  tags:
      - BaseX-9.2
  variables:
     GIT_STRATEGY: clone
     GIT_CLONE_PATH: $CI_BUILDS_DIR/vicav_webapp
     HOME: /home/gitlab-runner
  script:
    - $(npm bin)/cypress run

  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - $GIT_CLONE_PATH/cypress

clean-testbench:
  stage: cleanup
  tags:
      - BaseX-9.2
  variables:
     GIT_CLONE_PATH: $CI_BUILDS_DIR/vicav_webapp
  script:
    - rm -rf $GIT_CLONE_PATH 2>/dev/null
    - mkdir -p $GIT_CLONE_PATH 2>/dev/null
    - rm -rf $CI_BUILDS_DIR/vicav_content 2>/dev/null
  when: always